### ISSUE TITLE
NPE crash on VisitFormFragment0.kt

### ISSUE THREAD

**Issue by phillipsk** [BrightMindEnrichment/StreetCare#66]
FATAL EXCEPTION: main
                 Process: com.app.bmeapplication1, PID: 22948
                 java.lang.NullPointerException
                 	at org.brightmindenrichment.street_care.ui.visit.VisitFormFragment0.getBinding(VisitFormFragment0.kt:22)
                 	at org.brightmindenrichment.street_care.ui.visit.VisitFormFragment0$updateUI$1.invoke(VisitFormFragment0.kt:59)
                 	at org.brightmindenrichment.street_care.ui.visit.VisitFormFragment0$updateUI$1.invoke(VisitFormFragment0.kt:50)
                 	at org.brightmindenrichment.street_care.ui.visit.VisitDataAdapter$refresh$1.invoke(VisitDataAdapter.kt:93)
                 	at org.brightmindenrichment.street_care.ui.visit.VisitDataAdapter$refresh$1.invoke(VisitDataAdapter.kt:51)
                 	at org.brightmindenrichment.street_care.ui.visit.VisitDataAdapter.refresh$lambda$0(VisitDataAdapter.kt:51)
                 	at org.brightmindenrichment.street_care.ui.visit.VisitDataAdapter.$r8$lambda$WQUPnS6MGCZsnm641B17X_mcajE(Unknown Source:0)
                 	at org.brightmindenrichment.street_care.ui.visit.VisitDataAdapter$$ExternalSyntheticLambda1.onSuccess(Unknown Source:2)

Begin a visit log and then navigate to another screen and try navigating back to visit log

https://github.com/user-attachments/assets/18a535dd-7073-499c-8439-352ff8aa0241

**Comment by phillipsk** [comment]
Might need to be a new user with no existing visit logs
